# Generated by Django 4.1.2 on 2023-09-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('rating', models.IntegerField()),
                ('about', models.TextField()),
                ('genere', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('malayalam', 'Malayalam'), ('english', 'English'), ('hindi', 'Hindi'), ('tamil', 'Tamil')], max_length=10)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='movie_api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movie_api.movie')),
            ],
        ),
    ]
