# Generated by Django 4.1.2 on 2023-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
